//! Shared rendering utilities for TTD prompt templates.
//!
//! Ports the five mustache semantics used in the consensus templates into
//! native Rust string building (alzina has no mustache engine):
//!
//! 1. **Section iteration** `{{#list}}...{{/list}}` → Rust loop (empty list → nothing)
//! 2. **Inverted sections** `{{^last}}, {{/last}}` → comma-join via enumerate
//! 3. **Triple-mustache unescaped** `{{{fitness_feedback}}}` → raw string insert
//!    (no HTML escaping — the feedback document is engine-generated markdown,
//!    NOT free user text; T-23-05 mitigated)
//! 4. **Conditional** `{{#fitness_feedback}}...{{/fitness_feedback}}` → if let Some
//! 5. **Output discipline** "output ONLY the XML block" → preserved verbatim
//!
//! ## Trust boundary (T-23-06)
//!
//! Fitness-judge prompts must NOT have an "## Upstream context" preamble prepended
//! (Pitfall 6). They are constructed with empty ancestors so the render.rs channel-
//! substitution lexer does not inject its preamble. This is validated by
//! `ttd::prompts::tests::fitness_judge_no_preamble`.

/// Render a list of nodes as a markdown table for use in graph prompts.
///
/// Empty list → empty string (section-iteration semantics: `{{#nodes}}...{{/nodes}}`
/// renders nothing when `nodes` is empty).
pub fn render_nodes_section(nodes: &[(String, String)]) -> String {
    if nodes.is_empty() {
        return String::new();
    }
    let mut buf = String::new();
    buf.push_str("### Nodes\n\n");
    for (id, claim) in nodes {
        buf.push_str(&format!("- **[{id}]**: \"{claim}\"\n"));
    }
    buf
}

/// Render a list of edges as a markdown table for use in graph prompts.
pub fn render_edges_section(edges: &[(String, String, String)]) -> String {
    if edges.is_empty() {
        return String::new();
    }
    let mut buf = String::new();
    buf.push_str("### Edges\n\n");
    for (src, tgt, rel) in edges {
        buf.push_str(&format!("- **[{src}]** --[{rel}]--> {tgt}\n"));
    }
    buf
}

/// Render a list of sources with comma-joining.
///
/// Implements inverted-section semantics `{{^last}}, {{/last}}` from the
/// consensus templates: all items except the last get a trailing comma.
pub fn render_sources_comma_joined(sources: &[String]) -> String {
    sources
        .iter()
        .enumerate()
        .map(|(i, s)| {
            if i + 1 < sources.len() {
                format!("{s}, ")
            } else {
                s.clone()
            }
        })
        .collect()
}

/// Render a retrieved content list for gap_resolve prompts.
pub fn render_retrieved_section(retrieved: &[(String, String)]) -> String {
    if retrieved.is_empty() {
        return String::new();
    }
    let mut buf = String::new();
    buf.push_str("## Retrieved Content\n\n");
    for (source_id, content) in retrieved {
        buf.push_str(&format!("- Source {source_id}: \"{content}\"\n"));
    }
    buf
}

/// Render the fitness feedback block (unescaped, raw markdown).
///
/// This is the `{{{fitness_feedback}}}` triple-mustache section. The value is
/// injected RAW with no HTML escaping — `&amp;` / `&lt;` must NOT appear.
///
/// The fitness feedback document is engine-generated by `generate_feedback()`
/// (fitness.rs) with a fixed heading structure. It does NOT contain free user
/// text. T-23-05 is mitigated: the unescaped injection is safe because the
/// source is engine-controlled.
pub fn render_fitness_feedback_block(fitness_feedback: &Option<String>) -> String {
    match fitness_feedback {
        Some(feedback) if !feedback.is_empty() => {
            // Conditional section: `{{#fitness_feedback}}...{{/fitness_feedback}}`
            // wraps the triple-mustache `{{{fitness_feedback}}}` unescaped insert.
            format!(
                "## Fitness Evaluation Feedback\n\n\
                 The graph was evaluated and the following issues were identified:\n\n\
                 {feedback}\n\n\
                 Use this feedback to prioritize which gaps to address.\n"
            )
        }
        _ => String::new(), // Conditional section: renders nothing when absent/empty
    }
}

/// Render the fitness feedback block for gap_resolve prompts.
pub fn render_gap_resolve_feedback_block(fitness_feedback: &Option<String>) -> String {
    match fitness_feedback {
        Some(feedback) if !feedback.is_empty() => {
            format!(
                "## Fitness Evaluation Feedback\n\n\
                 {feedback}\n\n\
                 Address these issues in your refinement.\n"
            )
        }
        _ => String::new(),
    }
}

/// Render identified gaps as a markdown section.
pub fn render_gaps_section(gaps: &[(String, String)]) -> String {
    if gaps.is_empty() {
        return String::new();
    }
    let mut buf = String::new();
    buf.push_str("## Identified Gaps\n\n");
    for (description, query) in gaps {
        buf.push_str(&format!(
            "### Gap: {description}\n**Query used**: \"{query}\"\n\n"
        ));
    }
    buf
}
